version: '3.8'

services:
  app:
    build: .
    image: influencerpy:latest
    container_name: influencerpy_app
    volumes:
      - ./.influencerpy:/app/.influencerpy
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    command: bot
    restart: unless-stopped
    # depends_on:
    #   - db

  db:
    image: pgvector/pgvector:pg16
    container_name: influencerpy_db
    environment:
      POSTGRES_USER: influencerpy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: influencerpy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
